apiVersion: v1
kind: Service
metadata:
    name: "shcluster-0ea1"
    labels:
        app: "shcluster-0ea1"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "shcluster-0ea1"