apiVersion: v1
kind: Service
metadata:
    name: "shcluster-f4ba"
    labels:
        app: "shcluster-f4ba"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "shcluster-f4ba"